info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
dataSource:
  url: jdbc:mysql://localhost:3306/companion_project?serverTimezone=UTC&useSSL=false
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: '1234'
  dbCreate: update
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
